-- MySQL Script generated by MySQL Workbench
-- Tue Apr 24 12:04:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Salon_fryzjerski
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Salon_fryzjerski
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Salon_fryzjerski` DEFAULT CHARACTER SET utf8 ;
USE `Salon_fryzjerski` ;

-- -----------------------------------------------------
-- Table `Salon_fryzjerski`.`Klienci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Salon_fryzjerski`.`Klienci` (
  `idKlienci` INT NOT NULL,
  `imie` VARCHAR(80) NOT NULL,
  `nazwisko` VARCHAR(80) NOT NULL,
  `plec` VARCHAR(10) NOT NULL,
  `telefon` VARCHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `data` DATE NOT NULL,
  `godzina` DATETIME NOT NULL,
  `idusługi` INT NOT NULL,
  PRIMARY KEY (`idKlienci`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Salon_fryzjerski`.`Uslugi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Salon_fryzjerski`.`Uslugi` (
  `iduslugi` INT NOT NULL,
  `nazwa` VARCHAR(45) NULL,
  PRIMARY KEY (`iduslugi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Salon_fryzjerski`.`Kontakt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Salon_fryzjerski`.`Kontakt` (
  `idKontakt` INT NOT NULL,
  `imie` VARCHAR(80) NULL,
  `nazwisko` VARCHAR(80) NULL,
  `email` VARCHAR(100) NULL,
  `wiadomosc` LONGTEXT NULL,
  PRIMARY KEY (`idKontakt`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
