-- MySQL Script generated by MySQL Workbench
-- Fri Apr 20 11:39:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Salon_Fryzjerski
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Salon_Fryzjerski
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Salon_Fryzjerski` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `Salon_Fryzjerski` ;

-- -----------------------------------------------------
-- Table `Salon_Fryzjerski`.`Sklep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Salon_Fryzjerski`.`Sklep` ;

CREATE TABLE IF NOT EXISTS `Salon_Fryzjerski`.`Sklep` (
  `idSklep` INT NOT NULL,
  `idPracownik` INT NOT NULL,
  `idKlient` INT NOT NULL,
  `idDostawa` INT NOT NULL,
  PRIMARY KEY (`idSklep`, `idPracownik`, `idKlient`, `idDostawa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Salon_Fryzjerski`.`Rezerwacja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Salon_Fryzjerski`.`Rezerwacja` ;

CREATE TABLE IF NOT EXISTS `Salon_Fryzjerski`.`Rezerwacja` (
  `idRezerwacja` INT NOT NULL,
  `data` DATE NULL,
  `idklient` INT NOT NULL,
  `idUsług` INT NOT NULL,
  PRIMARY KEY (`idRezerwacja`, `idklient`, `idUsług`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Salon_Fryzjerski`.`Klient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Salon_Fryzjerski`.`Klient` ;

CREATE TABLE IF NOT EXISTS `Salon_Fryzjerski`.`Klient` (
  `Imie` VARCHAR(80) NULL,
  `Nazwisko` VARCHAR(80) NULL,
  `idUsługi` INT NOT NULL,
  `idDaneKontaktowe` INT NOT NULL,
  `idSklep` INT NOT NULL,
  `idRezerwacja` INT NOT NULL,
  `Rezerwacja_idRezerwacja` INT NOT NULL,
  `Rezerwacja_idklient` INT NOT NULL,
  `Rezerwacja_idPrawcownik` INT NOT NULL,
  `Rezerwacja_idUsług` INT NOT NULL,
  PRIMARY KEY (`idUsługi`, `idDaneKontaktowe`, `idSklep`, `idRezerwacja`),
  INDEX `fk_Klient_Sklep1_idx` (`idSklep` ASC),
  INDEX `fk_Klient_Rezerwacja1_idx` (`Rezerwacja_idRezerwacja` ASC, `Rezerwacja_idklient` ASC, `Rezerwacja_idPrawcownik` ASC, `Rezerwacja_idUsług` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Salon_Fryzjerski`.`Dane_Kontaktowe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Salon_Fryzjerski`.`Dane_Kontaktowe` ;

CREATE TABLE IF NOT EXISTS `Salon_Fryzjerski`.`Dane_Kontaktowe` (
  `idDane Kontaktowe` INT NOT NULL,
  `numerTelefonuKom` DECIMAL(9) NULL,
  `adresEmail` VARCHAR(45) NULL,
  `idPracownik` INT NOT NULL,
  `idKlient` INT NOT NULL,
  `Dane_Kontaktowecol` VARCHAR(45) NULL,
  PRIMARY KEY (`idDane Kontaktowe`, `idPracownik`, `idKlient`),
  INDEX `fk_Dane_Kontaktowe_Klient1_idx` (`idKlient` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Salon_Fryzjerski`.`Usługi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Salon_Fryzjerski`.`Usługi` ;

CREATE TABLE IF NOT EXISTS `Salon_Fryzjerski`.`Usługi` (
  `nazwaUsługi` VARCHAR(60) NULL,
  `idKoszty` INT NOT NULL,
  `idPracownik` INT NOT NULL,
  `idRezerwacja` INT NOT NULL,
  `idUsługi` INT NOT NULL,
  `idKlient` INT NOT NULL,
  PRIMARY KEY (`idKoszty`, `idPracownik`, `idUsługi`, `idKlient`, `idRezerwacja`),
  INDEX `fk_Usługi_Klient1_idx` (`idKlient` ASC),
  INDEX `fk_Usługi_Rezerwacja1_idx` (`idRezerwacja` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Salon_Fryzjerski`.`Pracownik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Salon_Fryzjerski`.`Pracownik` ;

CREATE TABLE IF NOT EXISTS `Salon_Fryzjerski`.`Pracownik` (
  `idPracownik` INT NOT NULL,
  `Imię` VARCHAR(80) NULL,
  `Nazwisko` VARCHAR(80) NULL,
  `idUsługi` INT NOT NULL,
  `idDaneKontaktowe` INT NOT NULL,
  `idSklep` INT NOT NULL,
  PRIMARY KEY (`idPracownik`, `idUsługi`, `idDaneKontaktowe`, `idSklep`),
  INDEX `fk_Pracownik_Dane_Kontaktowe1_idx` (`idDaneKontaktowe` ASC),
  INDEX `fk_Pracownik_Usługi1_idx` (`idUsługi` ASC),
  INDEX `fk_Pracownik_Sklep1_idx` (`idSklep` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Salon_Fryzjerski`.`Koszty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Salon_Fryzjerski`.`Koszty` ;

CREATE TABLE IF NOT EXISTS `Salon_Fryzjerski`.`Koszty` (
  `cenaProduktu` VARCHAR(10) NULL,
  `czasWykonania` VARCHAR(10) NULL,
  `idKoszty` INT NOT NULL,
  PRIMARY KEY (`idKoszty`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Salon_Fryzjerski`.`Dostawa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Salon_Fryzjerski`.`Dostawa` ;

CREATE TABLE IF NOT EXISTS `Salon_Fryzjerski`.`Dostawa` (
  `idDostawa` INT NOT NULL,
  `nazwaFirmy` VARCHAR(80) NULL,
  `produkty` VARCHAR(100) NULL,
  `dataDostawy` DATE NULL,
  `koszty` VARCHAR(20) NULL,
  PRIMARY KEY (`idDostawa`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
